### ISSUE TITLE
Database disk image is malformed from SQLite when using --num-processes > 0

### ISSUE THREAD

**Issue by jecor** [springmeyer/tilelite#1]
Sorry to report this here, but maybe the source of the error is important.

I was using tilelite happily with --num-processes=4 rendering a map with .shp files. I switched to SQLite/Spatialite instead, and I am now getting this kind of errors:

192.168.1.22 - - [17/Jul/2016 18:30:48] "GET /14/8351/5840.png HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 167, in execute
    for data in application_iter:
  File "/usr/share/pyshared/tilelite.py", line 364, in **call**
    mapnik.render(self._mapnik_map,im)
RuntimeError: SQLite Plugin: retrieving next row failed: database disk image is malformed

The sqlite files are read-only... Moreover, if i relaunch tilelite without --num-processes, I get all my rendered images without problems (albeit using only one core).

OS: Debian 8 with mapnik 2.2 on raspberry pi.

**Comment by springmeyer** [comment]
Mapnik builds a spatial index on first load, if it does not exist. It is likely this spatial index that is not getting written correctly. To workaround the problem I recommend:

 - Running first with `--num-processes=1` to ensure that only one process tries to create a spatial index.
 - Running with Mapnik >= 2.3.x to ensure https://github.com/mapnik/mapnik/issues/2483 is not causing problems.
  - Or, pass `auto_index=false` to disable spatial indexing on first load.
